cafe/urls.py
from django.urls import path, re_path
from .views import CafeHome, ShowDish

app_name = 'cafe'

urlpatterns = [
    path('', CafeHome.as_view(), name='home'),
    path('dish/<int:id>/<slug:slug>/', ShowDish.as_view(), name='dish'),
]

yummy/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from yummy import settings
from account.views import LoginUser, logout_user, RegisterUser

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cafe.urls')),

    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}{% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Amatic+SC:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">
</head>

<body>
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">
        <div class="container d-flex align-items-center justify-content-between">
            <a href="{% url 'cafe:home' %}" class="logo d-flex align-items-center me-auto me-lg-0">
                <h1>{{ title }}<span>.</span></h1>
            </a>
            {% include 'includes/messages.html' %}
            {% include 'includes/navbar.html' %}
            <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
            <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
        </div>
    </header>

    <!-- ======= Main Content ======= -->
    <main id="main">
        {% block content %}
        {% endblock %}
    </main>

    <!-- ======= Footer ======= -->
    {% include 'includes/footer.html' %}

    <a href="{% url 'cafe:home' %}" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script src="https://www.google.com/recaptcha/api.js"></script>
</body>
</html>

templates/inner.html
{% extends 'base.html' %}

{% block content %}
    <div class="breadcrumbs">
        <div class="container">
            <div class="d-flex justify-content-between align-items-center">
                <h2>{{ title }}</h2>
                <ol>
                    <li><a href="{% url 'cafe:home' %}">Home</a></li>
                    <li>{{ inner_title }}</li>
                </ol>
            </div>
        </div>
    </div>

    <section class="sample-page">
        <div class="container" data-aos="fade-up">
            {% block inner_content %}
            {% endblock %}    
        </div>
    </section>
{% endblock %}